---
- name: Create app directory
  file:
    path: $HOME/web
    state: directory

- name: "Copy files to server"
  ansible.builtin.copy:
    src: "files/artifact.tar.gz"
    dest: "$HOME/artifact.tar.gz"
    follow: true

- name: "install dependencies."
  become: true
  apt:
    name: 
      - nodejs
      - npm
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    state: latest


- name: extract artifact
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/

- name: Build
  become: true
  shell: |
    cd /home/ubuntu
    npm install
    npm run build

- name: "stop default"
  become: true
  command: sudo pm2 stop default

- name: "start the app"
  become: true
  command: sudo pm2 start npm -- run start



